### PR TITLE
Update ko-Kore_text.txt

### PR DESCRIPTION
**Pull request by tpae**
The encoding is broken, it's saved as EUC-KR not UTF-8.

The fonts look completely broken on the website: https://www.google.com/get/noto/#sans-kore

### CODE REVIEW

**Comment by tpae** [comment]
I signed it!

**Comment by dougfelt** [comment]
@jungshik, can you scan this and confirm it is ok?

**Comment by jungshik** [comment]
Do not merge. Nothing is wrong with the current version.

**Comment by tpae** [comment]
site looks broken to me..

**Comment by jungshik** [comment]
It is not udhr, but an excerpt from Hunminjeongeum that proclaimed the invention of a new script.

**Comment by jungshik** [comment]
What do you mean by 'broken'? The page has rendered images of the file.

**Comment by tpae** [comment]
I'm sorry for the misunderstanding.. I was not expecting Hunminjeongeum when I was looking for Korean text examples, caught me off guard. This is actually very fascinating, thank you for the contribution!

**Comment by dougfelt** [comment]
Thanks @jungshik.  I could not imagine you making this kind of mistake ;-)  Myself, on the other hand...

**Pull request closed without merging**
