### PR TITLE
Update cmap data with new info from Monotype.

### PR DESCRIPTION
**Pull request by dougfelt**
Some requested codepoints for Glagolitic, Gothic, and Kayah Li can
be used via fallback so will not be in these fonts.  In addition, the
following scripts have been checked and all their requested codepoints
will be in the fonts:

Avst - Avestan
Bamu - Bamun
Mand - Mandaic
Nkoo - N'Ko
Phli - Inscriptional Pahlavi
Prti - Inscriptional Parthian
Samr - Samaritan
Talu - New Tai Lue
Tfng - Tifinagh
Xpeo - Old Persian

Glag # Glagolitic
  removed, now in fallback (11): 0022 002c 002e 003b 00b7 201c-201d 2056 2058-2059 2e43
    Basic Latin
      0022 Zyyy Po 1.1 QUOTATION MARK (in Bass, Beng, Cans... Zmth)
      002c Zyyy Po 1.1 COMMA (in Arab, Aran, Bass... Zmth)
      002e Zyyy Po 1.1 FULL STOP (in Arab, Aran, Avst... Zmth)
      003b Zyyy Po 1.1 SEMICOLON (in Beng, Cham, Copt... Zmth)
    Latin-1 Supplement
      00b7 Zyyy Po 1.1 MIDDLE DOT (in Aran, Avst, Copt... Perm)
    General Punctuation
      201c Zyyy Pi 1.1 LEFT DOUBLE QUOTATION MARK (in Aran, Bass, Beng... Wara)
      201d Zyyy Pf 1.1 RIGHT DOUBLE QUOTATION MARK (in Aran, Bass, Beng... Wara)
      2056 Zyyy Po 4.1 THREE DOT PUNCTUATION (in LGC, MONO)
      2058 Zyyy Po 4.1 FOUR DOT PUNCTUATION (in LGC, MONO)
      2059 Zyyy Po 4.1 FIVE DOT PUNCTUATION (in LGC, MONO)
    Supplemental Punctuation
      2e43 Zyyy Po 9.0 DASH WITH LEFT UPTURN (Cyrl,Glag) (in LGC, MONO)
Goth # Gothic
  removed, now in fallback (2): 003a 00b7
    Basic Latin
      003a Zyyy Po 1.1 COLON (in Arab, Aran, Beng... Zmth)
    Latin-1 Supplement
      00b7 Zyyy Po 1.1 MIDDLE DOT (in Aran, Avst, Copt... Perm)
Kali # Kayah Li
  removed, now in fallback (6): 0021-0022 0028-0029 002c 003f
    Basic Latin
      0021 Zyyy Po 1.1 EXCLAMATION MARK (in Adlm, Arab, Aran... Zmth)
      0022 Zyyy Po 1.1 QUOTATION MARK (in Bass, Beng, Cans... Zmth)
      0028 Zyyy Ps 1.1 LEFT PARENTHESIS (in Aran, Beng, Cans... Zmth)
      0029 Zyyy Pe 1.1 RIGHT PARENTHESIS (in Aran, Beng, Cans... Zmth)
      002c Zyyy Po 1.1 COMMA (in Arab, Aran, Bass... Zmth)
      003f Zyyy Po 1.1 QUESTION MARK (in Beng, Cham, Deva... Zmth)
Tfng # Tifinagh
  removed, now in fallback (5): 0022 00ab 00bb 201d-201e
    Basic Latin
      0022 Zyyy Po 1.1 QUOTATION MARK (in Bass, Beng, Cans... Zmth)
    Latin-1 Supplement
      00ab Zyyy Pi 1.1 LEFT-POINTING DOUBLE ANGLE QUOTATION MARK (in Arab, Aran, Khmr... Syrc)
      00bb Zyyy Pf 1.1 RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK (in Arab, Aran, Khmr... Syrc)
    General Punctuation
      201d Zyyy Pf 1.1 RIGHT DOUBLE QUOTATION MARK (in Aran, Bass, Beng... Wara)
      201e Zyyy Ps 1.1 DOUBLE LOW-9 QUOTATION MARK (in LGC, MONO)

### CODE REVIEW

**Comment by dougfelt** [comment]
This will fix nototools#425

**Comment by dougfelt** [comment]
These are included in the cmap because either the Unicode spec or cldr data indicates that the punctuation is used with some languages written with the script.

We then request Monotype to investigate these characters and make a determination whether they need special treatment or can fall back to the LGC shapes/positions/advances.

When Monotype looks at a script for this, they annotate the spreadsheet-- the entire column to indicate they've reviewed the script, and particular codepoints in the column to indicate those codepoints can be supported by fallback to LGC.

I take their annotated spreadsheet and parse out this data, encoding it into the xml file so the noto tools (in particular, noto_lint) can use it.  This way we have a record both of what characters we originally requested and which ones we actually expect to be in the font.  We can also regenerate the spreadsheet from the xml.

So, in particular reference to your questions:
1) Monotype is asserting that the glyphs are no different from the corresponding ones in LGC. If someone files a bug, of course, we can request changes, but initially we accept their recommendation.
2) Our plans haven't changed.  It is our intent to specify these explicitly so Monotype will know which characters to look at.  As you recall, they were not happy with our early suggestion that they just review all of LGC with an eye to any characters that might be used with the script.
3) This is no accident, these are included intentionally for this very purpose.

**Comment by roozbehp** [comment]
Question: do any of the glyphs interact with glyphs next to them (kerning etc)?

**Comment by dougfelt** [comment]
They're punctuation.  I haven't examined the fonts personally.  Monotype has been told that kerning is one of the issues we're interested in.

**Comment by jungshik** [comment]
Given what @dougfelt  wrote, LGTM.

**Pull request merged**
