### PR TITLE
notodiff addition and improvement

### PR DESCRIPTION
**Pull request by jamesgk**

### CODE REVIEW

**Comment by dougfelt** [comment]
LGTM

BTW, nothing in the file appears to describe the different types of comparison and why you'd choose one over the other.  Is there some other document that describes this?

**Comment by jamesgk** [comment]
I put a little bit of information at the top of shape_diff.py. Maybe that info should be expanded and/or put into notodiff.py.

**Comment by dougfelt** [comment]
Thanks.  Still LGTM...

**Comment by jamesgk** [comment]
Yikes, forgot about this.

**Pull request merged**
